### PR TITLE
Remove now unsupported Oracle JDK 7 Travis target (bug 2766)

### PR DESCRIPTION
**Pull request by adamburkegh**
See links and detail in https://bugs.jython.org/issue2766

### CODE REVIEW

**Comment by adamburkegh** [comment]
Travis issue for ref https://github.com/travis-ci/travis-ci/issues/7884

**Comment by jeff5** [comment]
This tests itself so will commit via hg. Work that actually turns these green would be welcome (with care taken to convert skips to issues).

**Comment by jeff5** [comment]
Now in at https://hg.python.org/jython/rev/525e6665e226

Thanks Adam.

**Comment by adamburkegh** [comment]
Cheers @jeff5

**Pull request closed without merging**
