### PR TITLE
Replace deprecated use of ASCII constant with ascii()

### PR DESCRIPTION
**Pull request by jamesmudd**
This is now deprecated in Guava and will be removed in June 2018

### CODE REVIEW

**Comment by Stewori** [comment]
Looks good to me; I briefly reviewed and suppose these changes are pretty safe and regrtests go fine.

Merged as of https://hg.python.org/jython/rev/72a72b948afb. Can be closed.

For some reason this wasn't yet mirrored back to github for some hours. (Maybe our sync process is somehow broken?) Anyway, it's in official trunk now.

**Comment by jamesmudd** [comment]
Thanks that's great I will close this PR. Just a question on the CI do you expect these builds to be passing? Or is it something that needs work?

**Comment by Stewori** [comment]
The CI is currently not reliable. This may be due to edgy Java 8 support in Jython, i.e. building with Java 8 currently needs trickery because of antlr 3, see https://github.com/jythontools/jython/issues/51 and also regrtests have issues, e.g. see http://bugs.jython.org/issue2399. In addition to that, already in Java 7 some regrtests are unstable (e.g. socket stuff). I don't know about our CI config in detail, @darjus is doing that AFAIK, but I guess the CI failures come from these things.

**Comment by jeff5** [comment]
Raised as jythontools/jython PR 55

**Pull request closed without merging**
