### PR TITLE
Accept annotations in org.python.compiler.ClassFile#addField

### PR DESCRIPTION
**Pull request by cpburnz**
Currently `org.python.compiler.ClassFile#addField` does not accept annotations (`org.python.compiler.ProxyCodeHelpers.AnnotationDescr`) as an argument. The underlying `org.objectweb.asm.FieldVisitor` supports annotations however. I added a new overload to `addField` to accept annotations, and pass them on to `FieldVisitor` similar to how they are passed for methods in `ClassFile#addMethod`.

### CODE REVIEW

**Comment by jimbaker** [comment]
+1, sounds reasonable to me

**Comment by jimbaker** [comment]
Caleb, this is a small PR, but please sign our contributor agreement: https://www.python.org/psf/contrib/contrib-form/ Thanks!

**Comment by cpburnz** [comment]
@jimbaker I signed the contributor agreement.

**Comment by darjus** [comment]
I know it's been a while but i merged the change.

**Pull request closed without merging**
