### PR TITLE
support unicode exception

### PR DESCRIPTION
**Pull request by yishenggudou**
support unicode jdbc Error Exception

### CODE REVIEW

**Comment by jeff5** [comment]
That looks good to me. Thanks for spotting it.

I think this is too small to bother you for a contributor form.

Our master repo is still Mercurial, so we don't commit via GitHub, but as a patch, which I'll take care of.

The tools we use don't handle Chinese very well, although we try to do better in Jython itself. Is "Kui Seng" (or "Kuì Sēng (愧僧)") an acceptable representation of your name in ACKNOWLEDGMENTS and the repo? Or is that something entirely different?

**Comment by yishenggudou** [comment]
Thank you for reply
you can use my github name

**Comment by jeff5** [comment]
Done the right way, Mercurial turns out to be ok with Unicode. Now at https://github.com/jythontools/jython/commit/379c6fa9334ede2627567e60b3b8bb60da8d80a1, thanks again.

**Comment by jeff5** [comment]
Raised as jythontools/jython pull 131

**Pull request closed without merging**
