### PR TITLE
Fix calling Java vararg methods with no arguments fails

### PR DESCRIPTION
**Pull request by jamesmudd**
Also add additional testing for vararg methods to improve test coverage
of boxing varargs.

### CODE REVIEW

**Comment by darjus** [comment]
Hey James, do you have a PSF contributor agreement signed? If not, I'll need you to sign it before accepting the patch: https://www.python.org/psf/contrib/contrib-form/

**Comment by jamesmudd** [comment]
Thanks. I have now completed the PSF contributor agreement.

**Comment by jamesmudd** [comment]
This change has been merged in without accepting the pull request so closing it. Thanks

**Comment by jeff5** [comment]
Raised as jythontools/jython pull 50

**Pull request closed without merging**
